### ISSUE TITLE
Automatically disconnect from the network

### ISSUE THREAD

**Issue by hoaug-tran** [Shaneee/AppleIGB#4]
Hi,

i have X570 with I211-AT installed Ventura. This kext have a issue is Automatically disconnect from the network and reconnect it after some second, it's quite annoying. is there anyway to fix it? thank you so much.

**Comment by marekk1717** [comment]
I have the same issue

**Comment by eppjohnny** [comment]
Some for me, but with Sonoma

**Comment by hoaug-tran** [comment]
@eppjohnny the issue maybe due to kext, idk why Shaneee not check this issue, maybe he busy or he was drop this project

**Comment by eppjohnny** [comment]
@hoaug-tran I never coded a kext, but would like to contribute / help… and also support everyone with a X570 mainboard. Maybe I will investigate further. But at first I need to find out how to troubleshoot.

**Comment by Shaneee** [comment]
I personally use this version. Check the main readme though, https://github.com/donatengit/AppleIGB/releases/tag/v5.11-mb
